// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAISAFJ9MHf96oF_z8oB3q60ZQfKCdU1qs',
    appId: '1:170642391764:web:84153fce384a4c8f8eb141',
    messagingSenderId: '170642391764',
    projectId: 'mathsum-quest',
    authDomain: 'mathsum-quest.firebaseapp.com',
    storageBucket: 'mathsum-quest.appspot.com',
    measurementId: 'G-YN2JH24HMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDALt55UJpKch-qJSdjePghJ7l3L9N5CVQ',
    appId: '1:170642391764:android:c2bd63467d175a338eb141',
    messagingSenderId: '170642391764',
    projectId: 'mathsum-quest',
    storageBucket: 'mathsum-quest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9oKAn_fKiN4GlHvTy9Z3G5uC8Fta9LbY',
    appId: '1:170642391764:ios:13f9b0d4d7cbd8078eb141',
    messagingSenderId: '170642391764',
    projectId: 'mathsum-quest',
    storageBucket: 'mathsum-quest.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
